// Liste des pays proposés au client pour le numéro (numéros virtuels et abonnements).
export const countries = [
  "Niger",
  "Nigeria",
  "Bénin",
  "Burkina Faso",
  "Mali",
  "Sénégal",
  "Côte d'Ivoire",
  "Togo",
  "Ghana",
  "Cameroun",
  "Tchad",
  "Guinée",
  "Mauritanie",
  "Maroc",
  "Algérie",
  "Tunisie",
  "Égypte",
  "Afrique du Sud",
  "Kenya",
  "Congo (RDC)",
  "France",
  "Belgique",
  "Espagne",
  "Italie",
  "Allemagne",
  "Royaume-Uni",
  "Pays-Bas",
  "Portugal",
  "Turquie",
  "Émirats arabes unis",
  "Arabie saoudite",
  "Qatar",
  "Inde",
  "Indonésie",
  "Philippines",
  "Chine",
  "Brésil",
  "Argentine",
  "Mexique",
  "Canada",
  "États-Unis",
  "Australie",
] as const;
