/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as CommanderRouteImport } from './routes/commander'
import { Route as SuiviRouteImport } from './routes/suivi'
import { Route as CommandeRefRouteImport } from './routes/commande.$ref'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const CommanderRoute = CommanderRouteImport.update({
  id: '/commander',
  path: '/commander',
  getParentRoute: () => rootRouteImport,
} as any)
const SuiviRoute = SuiviRouteImport.update({
  id: '/suivi',
  path: '/suivi',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandeRefRoute = CommandeRefRouteImport.update({
  id: '/commande/$ref',
  path: '/commande/$ref',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogue': typeof CatalogueRoute
  '/commander': typeof CommanderRoute
  '/suivi': typeof SuiviRoute
  '/commande/$ref': typeof CommandeRefRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogue': typeof CatalogueRoute
  '/commander': typeof CommanderRoute
  '/suivi': typeof SuiviRoute
  '/commande/$ref': typeof CommandeRefRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalogue': typeof CatalogueRoute
  '/commander': typeof CommanderRoute
  '/suivi': typeof SuiviRoute
  '/commande/$ref': typeof CommandeRefRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/catalogue' | '/commander' | '/suivi' | '/commande/$ref'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/catalogue' | '/commander' | '/suivi' | '/commande/$ref'
  id:
    '__root__' | '/' | '/catalogue' | '/commander' | '/suivi' | '/commande/$ref'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogueRoute: typeof CatalogueRoute
  CommanderRoute: typeof CommanderRoute
  SuiviRoute: typeof SuiviRoute
  CommandeRefRoute: typeof CommandeRefRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commander': {
      id: '/commander'
      path: '/commander'
      fullPath: '/commander'
      preLoaderRoute: typeof CommanderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suivi': {
      id: '/suivi'
      path: '/suivi'
      fullPath: '/suivi'
      preLoaderRoute: typeof SuiviRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commande/$ref': {
      id: '/commande/$ref'
      path: '/commande/$ref'
      fullPath: '/commande/$ref'
      preLoaderRoute: typeof CommandeRefRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogueRoute: CatalogueRoute,
  CommanderRoute: CommanderRoute,
  SuiviRoute: SuiviRoute,
  CommandeRefRoute: CommandeRefRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
